# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initpdyn <- function(dm_, srec_, psi_, M_, mata_, wta_, sela_, hinit_) {
    .Call(`_abctuna_initpdyn`, dm_, srec_, psi_, M_, mata_, wta_, sela_, hinit_)
}

msypdyn <- function(dm_, srec_, R0_, hh_, psi_, M_, mata_, wta_, sela_, hinit_) {
    .Call(`_abctuna_msypdyn`, dm_, srec_, R0_, hh_, psi_, M_, mata_, wta_, sela_, hinit_)
}

pdyn <- function(dm_, srec_, R0_, hh_, psi_, epsr_, spr0_, M_, mata_, wta_, sela_, Ninit_, Cb_) {
    .Call(`_abctuna_pdyn`, dm_, srec_, R0_, hh_, psi_, epsr_, spr0_, M_, mata_, wta_, sela_, Ninit_, Cb_)
}

pdynlfcpue <- function(dm_, srec_, R0_, hh_, psi_, epsr_, spr0_, M_, mata_, wta_, sela_, Ninit_, Cb_, pla_, fref_) {
    .Call(`_abctuna_pdynlfcpue`, dm_, srec_, R0_, hh_, psi_, epsr_, spr0_, M_, mata_, wta_, sela_, Ninit_, Cb_, pla_, fref_)
}

